name: Activate Unity
on: repository_dispatch
jobs:
  requestActivation:
    name: Request activation ✔
    runs-on: ubuntu-latest
    steps:
      - name: Activate Unity
        if: github.event.action == 'request_activation_file'
        uses: webbertakken/unity-activate@v1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_ALF }}
        with:
          unityVersion: 2018.4.13f1
