name: Test and Build

on: repository_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    if: github.event.action == 'test_and_build'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - project
        unityVersion:
          - 2018.4.13f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- iOS # Build an iOS player.
          #- WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1 # cache方法用於儲存/還原快取檔，用以加速運行。
        with:
          path: ${{ matrix.projectPath }}/Library # 這裡我們用來快取Unity的Library資料夾，以防每次重開專案都要花時間建置Library資料夾。
          key: Library-path_${{ matrix.projectPath }}_-${{ matrix.targetPlatform }}-${{ github.workflow }} # key即identifier，存取時仰賴這組key來取得cache，這裡的key為Library-<project_path>-<os>-<workflow_name>。
          restore-keys: | # Restore用的備選key，如果hit不到原key會試圖找以下的key
            Library-path_${{ matrix.projectPath }}_-${{ matrix.targetPlatform }}-
      - uses: webbertakken/unity-test-runner@v1.4.1
        id: testRunner
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          customParameters: -buildTarget ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.targetPlatform }} Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
      - uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          #customParameters: "-myParameter myValue -myBoolean -ThirdParameter andItsValue"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.targetPlatform }} Build
          path: build
